### ISSUE TITLE
Fix docs.rs builds

### ISSUE THREAD

**Issue by ShadowJonathan** [sanpii/lxc-rs#10]
https://docs.rs/crate/lxc/0.4.3

Currently docs.rs builds are failing because the `lxc` dependency isnt added to the build environment, see [here](https://forge.rust-lang.org/docs-rs/add-dependencies.html)

**Comment by sanpii** [comment]
Thank you for your help!

**Comment by sanpii** [comment]
https://docs.rs/lxc/0.5.0/lxc/ :tada:
