### ISSUE TITLE
Allow using raw APIs with ergonomic structures

### ISSUE THREAD

**Issue by koutheir** [sanpii/lxc-rs#11]
Using Rust ergonomic safe structures, such as `lxc::Container` is the point of using the `lxc` crate. Thank you for offering this.

However, sometimes, one wants to call some raw APIs from `lxc-sys` even when using ergonomic structures most of the time. In order to do this, one needs access to the `liblxc` data encapsulated by the ergonomic structures, such as pointers and the like.

Can you please provide a way to do this, such as implementing `as_ptr()`, `as_mut_ptr()` methods on ergonomic structures?

**Comment by sanpii** [comment]
https://github.com/sanpii/lxc-rs/pull/13

Let me know if it’s good for you.

**Comment by koutheir** [comment]
The changes look right. Thank you for your efforts!
