### ISSUE TITLE
lxc::Container::new implementation is unsafe

### ISSUE THREAD

**Issue by Thog** [sanpii/lxc-rs#17]
Hello there,

As per [documentation](https://github.com/lxc/lxc/blob/38386b4794d9757787ef6068515cfd92a329ed3b/src/lxc/lxccontainer.h#L1010-L1018), ``lxc_container_new`` can return ``NULL`` in case of errors.

At the current time of writing the [current implementation](https://github.com/sanpii/lxc-rs/blob/f267180ba72d9146be7c793d81d9080c718f6051/src/container.rs#L113) of ``lxc::Container::new`` doesn't check the returned pointer resulting in no error reporting and possible deference of ``self.inner``.

**Comment by sanpii** [comment]
Fixed, thank you.
