### ISSUE TITLE
'lxc/lxccontainer.h' file not found while compiling lxc-sys

### ISSUE THREAD

**Issue by Murugesh-R** [sanpii/lxc-rs#30]
I added lxc:0.7.0 in cargo.toml. while trying to run the project, i am getting this error.

Compiling lxc-sys v0.5.0
error: failed to run custom build command for `lxc-sys v0.5.0`

Caused by:
  process didn't exit successfully: `/home/target/debug/build/lxc-sys-5eadf5c24bf790c8/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=lxc

  --- stderr
  wrapper.h:1:10: fatal error: 'lxc/lxccontainer.h' file not found
  thread 'main' panicked at /home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lxc-sys-0.5.0/build.rs:7:10:
  Unable to generate bindings: ClangDiagnostic("wrapper.h:1:10: fatal error: 'lxc/lxccontainer.h' file not found\n")
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sanpii** [comment]
Have you installed the package for lxc (and the lxc-dev if your distribution have one)?

**Comment by Murugesh-R** [comment]
After installing lxc-dev, it is working fine. thank you.
